name: 'Manele Code Smell Scanner'
description: 'Detects code smells in a C/C++ code base.'
author: 'Elena Marzi Tornblad'
branding:
  icon: code
  color: green
input:
  source-location:
    description: 'Root directory of source code'
    required: true
    default: 'src'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: 'Install Clang (Linux)'
      if: ${{ env.RUNNER_OS == 'Linux' }}
      run: apt-get install clang
    - name: 'Install Clang (macOS)'
      if: ${{ env.RUNNER_OS == 'macOS' }}
      run: brew install clang
    - name: 'Install Clang (Windows)'
      if: ${{ env.RUNNER_OS == 'Windows' }}
      run: choco install clang
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install libclang
    - run: python ${{ github.action_path }}/sniff.py ${{ inputs.source-location }}

