name: 'Manele Code Smell Scanner'
description: 'Detects code smells in a C/C++ code base.'
author: 'Elena Marzi Tornblad'
branding:
  icon: code
  color: green
input:
  source-location:
    description: 'Root directory of source code'
    required: true
    default: 'src'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: 'Select shell'
      id: select_shell
      with:
        cond: ${{ runner.os == 'Windows' }}
        if_true: 'cmd'
        if_false: 'bash'
    - name: 'Install Clang (Linux)'
      if: ${{ runner.os == 'Linux' }}
      run: apt-get install clang
      shell: bash
    - name: 'Install Clang (macOS)'
      if: ${{ runner.os == 'macOS' }}
      run: brew install clang
      shell: bash
    - name: 'Install Clang (Windows)'
      if: ${{ runner.os == 'Windows' }}
      run: choco install clang
      shell: cmd
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install libclang
      shell: ${{ steps.select_shell.outputs.value }}
    - run: python ${{ github.action_path }}/sniff.py ${{ inputs.source-location }}
      shell: ${{ steps.select_shell.outputs.value }}

