name: 'Manele Code Smell Scanner'
description: 'Detects code smells in a C/C++ code base.'
author: 'Elena Marzi Tornblad'
branding:
  icon: code
  color: green
inputs:
  source-location:
    description: 'Root directory of source code'
    required: true
    default: 'src'
runs:
  using: "composite"
  steps:
    - name: 'Install Clang (Linux)'
      if: runner.os == 'Linux'
      run: apt-get install clang
      shell: bash
    - name: 'Install Clang (macOS)'
      if: runner.os == 'macOS'
      run: brew install clang
      shell: bash
    - name: 'Install Clang (Windows)'
      if: runner.os == 'Windows'
      run: choco install clang
      shell: cmd
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install libclang
      if: runner.os == 'Windows'
      shell: cmd
    - run: dir /s ${{ github.action_path }}
      if: runner.os == 'Windows'
      shell: cmd
    - run: python ${{ github.action_path }}/sniff.py ${{ inputs.source-location }}
      if: runner.os == 'Windows'
      shell: cmd
    - run: pip install libclang
      shell: bash
    - run: python ${{ github.action_path }}/sniff.py ${{ inputs.source-location }}
      shell: bash

